---
- name: Self-Healing Playbook for Garbage Collection in Azure Red Hat OpenShift
  hosts: localhost
  become: true
  vars:
    oc_bin: /usr/local/bin/oc
    namespace: default
    problematic_pod_label: app=garbage-collector
    selective_label: existing-label=your-value
    azure_subscription_id: your_subscription_id
    key_vault_name: your_key_vault_name
    secret_name: your_secret_name
    aro_api_url: your_aro_api_url
    app_id: your_service_principal_id
    tenant_id: your_tenant_id
    client_secret: your_client_secret

  tasks:
    - name: Log in to Azure
      azure_rm_auth:
        client_id: "{{ app_id }}"
        secret: "{{ client_secret }}"
        tenant: "{{ tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"

    - name: Get OpenShift token from Key Vault
      azure_rm_keyvaultsecret_info:
        vault_uri: "https://{{ key_vault_name }}.vault.azure.net"
        secret_name: "{{ secret_name }}"
      register: secret_info

    - name: Set ARO token fact
      set_fact:
        aro_token_value: "{{ secret_info.secrets[0].value }}"

    - name: Log in to OpenShift
      shell: "{{ oc_bin }} login --token={{ aro_token_value }} --server={{ aro_api_url }}"
      register: oc_login

    - name: Ensure OpenShift login was successful
      fail:
        msg: "OpenShift login failed"
      when: oc_login.rc != 0

    - name: Add label to selected pods
      shell: "{{ oc_bin }} get pods -l {{ selective_label }} -n {{ namespace }} -o name | xargs -I {} {{ oc_bin }} label {} {{ problematic_pod_label }}"
      register: label_output

    - name: Check for Garbage Collector issues
      shell: "{{ oc_bin }} logs -l {{ problematic_pod_label }} -n {{ namespace }} | grep -i 'error'"
      register: gc_logs
      failed_when: false

    - name: Determine if action is needed
      set_fact:
        action_needed: "{{ gc_logs.stdout != '' }}"

    - name: Notify if no issues found
      debug:
        msg: "No garbage collector issues found."
      when: not action_needed

    - name: Restart problematic pods
      shell: "{{ oc_bin }} delete pod -l {{ problematic_pod_label }} -n {{ namespace }}"
      when: action_needed

    - name: Scale replicas up
      shell: "{{ oc_bin }} scale deployment {{ problematic_pod_label }} --replicas=3 -n {{ namespace }}"
      when: action_needed

    - name: Verify pods are running
      shell: "{{ oc_bin }} get pods -l {{ problematic_pod_label }} -n {{ namespace }}"
      register: pod_status

    - name: Wait for pods to be running
      wait_for:
        timeout: 300
        delay: 15
        state: started
        search_regex: "Running"
        path: /dev/null
      when: "'Running' not in pod_status.stdout"
