---
  - name: Retrieve credentials from KeyVault  # Nome da tarefa: Recuperar credenciais do KeyVault
    azure_rm_keyvaultsecret_info:
      vault_url: "https://your-keyvault-url.vault.azure.net/"  # URL do KeyVault
      secret_name: "cyberark-credentials"  # Nome do segredo a ser recuperado
      client_id: "your-client-id"  # ID do cliente para autenticação
      client_secret: "your-client-secret"  # Segredo do cliente para autenticação
      tenant: "your-tenant-id"  # ID do locatário para autenticação
    register: keyvault_credentials  # Registrar a saída na variável keyvault_credentials
  
  - name: Set CyberArk credentials as environment variables  # Nome da tarefa: Definir credenciais do CyberArk como variáveis de ambiente
    set_fact:
      cyberark_username: "{{ keyvault_credentials['secrets']['username'] }}"  # Definir o nome de usuário do CyberArk
      cyberark_password: "{{ keyvault_credentials['secrets']['password'] }}"  # Definir a senha do CyberArk
  
  - name: Logon to CyberArk Vault  # Nome da tarefa: Fazer login no CyberArk Vault
    cyberark_authentication:
      api_base_url: "http://components.cyberark.local"  # URL base da API do CyberArk
      validate_certs: false  # Não validar certificados
      username: "bizdev"  # Nome de usuário para autenticação
      password: "Cyberark1"  # Senha para autenticação
    register: cyberark_session  # Registrar a sessão na variável cyberark_session
    
  - name: Creating an Account using the PAS WebServices SDK  # Nome da tarefa: Criar uma conta usando o PAS WebServices SDK
    cyberark_account:
      logging_level: DEBUG  # Nível de log: DEBUG
      identified_by: "address,username"  # Identificar a conta por endereço e nome de usuário
      safe: "Test"  # Nome do cofre (safe)
      address: "cyberark.local"  # Endereço da conta
      username: "administrator-x"  # Nome de usuário da conta
      platform_id: WinServerLocal  # ID da plataforma
      secret: "@N&Ibl3!"  # Senha da conta
      platform_account_properties:
        LogonDomain: "cyberark"  # Domínio de logon
        OwnerName: "ansible_user"  # Nome do proprietário
      secret_management:
        automatic_management_enabled: true  # Gerenciamento automático habilitado
      state: present  # Estado desejado: presente
      cyberark_session: "{{ cyberark_session }}"  # Sessão do CyberArk
    register: cyberarkaction  # Registrar a ação na variável cyberarkaction
    
  - name: Rotate credential via reconcile and providing the password to be changed to  # Nome da tarefa: Rotacionar credencial via reconciliação e fornecer a nova senha
    cyberark_account:
      identified_by: "address,username"  # Identificar a conta por endereço e nome de usuário
      safe: "Domain_Admins"  # Nome do cofre (safe)
      address: "prod.cyberark.local"  # Endereço da conta
      username: "admin"  # Nome de usuário da conta
      platform_id: WinDomain  # ID da plataforma
      platform_account_properties:
        LogonDomain: "PROD"  # Domínio de logon
      secret_management:
        new_secret: "Ama123ah12@#!Xaamdjbdkl@#112"  # Nova senha
        management_action: "reconcile"  # Ação de gerenciamento: reconciliação
        automatic_management_enabled: true  # Gerenciamento automático habilitado
      state: present  # Estado desejado: presente
      cyberark_session: "{{ cyberark_session }}"  # Sessão do CyberArk
    register: reconcileaccount  # Registrar a ação na variável reconcileaccount
    
  - name: Logoff from CyberArk Vault  # Nome da tarefa: Fazer logoff do CyberArk Vault
    cyberark_authentication:
      state: absent  # Estado desejado: ausente
      cyberark_session: "{{ cyberark_session }}"  # Sessão do CyberArk