---
  - name: Download OneAgent installer using PowerShell
    win_shell: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;
      Invoke-WebRequest -Uri '{{ dynatrace_environment_url }}/api/v1/deployment/installer/agent/windows/default/latest?arch=x86' -Headers @{ 'Authorization' = 'Api-Token {{ dynatrace_api_token }}' } -OutFile '{{ oneagent_installer_path }}'

  - name: Install OneAgent
    win_shell: "{{ oneagent_installer_path }} --set-monitoring-mode=fullstack --set-app-log-content-access=true /quiet /norestart"
    args:
      creates: "{{ oneagent_expected_path }}"

  - name: Validate OneAgent service installation
    win_service:
      name: "{{ oneagent_service_name }}"
    register: oneagent_service

  - name: Check if OneAgent service is running
    win_service_info:
      name: "{{ oneagent_service_name }}"
    register: oneagent_service_info

  - name: Check if OneAgent service is running
    assert:
      that:
        - oneagent_service.status == 'running'
      fail_msg: "OneAgent service is not running."