---
# tasks/retrieve_password.yml
- name: Retrieve credentials from KeyVault
  azure_rm_keyvaultsecret_info:
    vault_url: "{{ vault_url }}"
    secret_name: "{{ secret_name }}"
    client_id: "{{ client_id }}"
    client_secret: "{{ client_secret }}"
    tenant: "{{ tenant }}"
  register: keyvault_credentials

- name: Set CyberArk credentials as environment variables
  set_fact:
    cyberark_username: "{{ keyvault_credentials.secrets.username }}"
    cyberark_password: "{{ keyvault_credentials.secrets.password }}"