---
- name: Retrieve credentials from KeyVault
  azure_rm_keyvaultsecret_info:
    vault_url: "{{ vault_url }}" # URL do KeyVault
    secret_name: "{{ secret_name }}" # Nome do segredo a ser recuperado
    client_id: "{{ client_id }}" # ID do cliente para autenticação
    client_secret: "{{ client_secret }}" # Segredo do cliente para autenticação
    tenant: "{{ tenant }}" # ID do locatário para autenticação
  register: keyvault_credentials # Registrar a saída na variável keyvault_credentials

- name: Set CyberArk credentials as environment variables
  set_fact:
    cyberark_username: "{{ keyvault_credentials.secrets.username }}" # Definir o nome de usuário do CyberArk
    cyberark_password: "{{ keyvault_credentials.secrets.password }}" # Definir a senha do CyberArk