---
# tasks/rotate_credential.yml
- name: Rotate credential via reconcile and providing the password to be changed to
  cyberark_account:
    identified_by: "address,username"
    safe: "{{ cyberark_safe }}"
    address: "{{ cyberark_address }}"
    username: "{{ cyberark_username }}"
    platform_id: "{{ cyberark_platform_id }}"
    platform_account_properties:
      LogonDomain: "{{ cyberark_logon_domain }}"
    secret_management:
      new_secret: "{{ cyberark_new_secret }}"
      management_action: "reconcile"
      automatic_management_enabled: true
    state: present
    cyberark_session: "{{ cyberark_session }}"
  register: reconcileaccount